//! Generates `PARITY.md`, the public Vim/Neovim parity scoreboard, from the
//! keybind coverage inventory and the vim-oracle case tables. A staleness test
//! keeps the committed file byte-identical to what these inventories produce,
//! so the published claims can never drift from what the suite verifies.

use crate::keybind_coverage::{self, CoverageKind, CoverageState, KeybindCoverage};
use crate::vim_oracle;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const PARITY_PATH: &str = "PARITY.md";

fn manifest_path(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(relative)
}

/// Implemented/planned keybind counts from the `**Status:**` line in
/// KEYBINDS_ROADMAP.md — the single hand-maintained source for those totals.
fn roadmap_counts() -> (usize, usize) {
    let text =
        fs::read_to_string(manifest_path("KEYBINDS_ROADMAP.md")).expect("read KEYBINDS_ROADMAP.md");
    let status = text
        .lines()
        .find(|line| line.trim_start().starts_with("**Status:"))
        .expect("KEYBINDS_ROADMAP.md is missing its `**Status:` line");
    let mut numbers = status
        .split(|c: char| !c.is_ascii_digit())
        .filter(|chunk| !chunk.is_empty())
        .map(|chunk| chunk.parse::<usize>().expect("status count fits in usize"));
    let implemented = numbers
        .next()
        .expect("status line lists the implemented keybind count first");
    let planned = numbers
        .next()
        .expect("status line lists the planned keybind count second");
    (implemented, planned)
}

/// The Neovim version CI pins for the real-nvim oracle runs, read from the
/// workflow so the scoreboard can't advertise a version CI no longer tests.
fn ci_nvim_version() -> String {
    let text = fs::read_to_string(manifest_path(".github/workflows/rust.yml"))
        .expect("read .github/workflows/rust.yml");
    text.lines()
        .filter_map(|line| line.trim().strip_prefix("version: "))
        .find(|value| value.starts_with('v'))
        .expect("CI workflow no longer pins an nvim version (`version: vX.Y.Z`)")
        .to_string()
}

/// GFM table cells treat `|` as a column break even inside code spans.
fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn push_table(
    out: &mut String,
    value_header: &str,
    entries: &[&KeybindCoverage],
    test_id_of: impl Fn(&KeybindCoverage) -> &'static str,
) {
    let _ = writeln!(out, "| Keybind | Behavior | {value_header} |");
    let _ = writeln!(
        out,
        "|---------|----------|{}|",
        "-".repeat(value_header.len())
    );
    for entry in entries {
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}` |",
            escape_cell(entry.key),
            escape_cell(entry.description),
            escape_cell(test_id_of(entry)),
        );
    }
    out.push('\n');
}

fn render() -> String {
    let entries = keybind_coverage::coverage_entries();
    let (implemented, planned) = roadmap_counts();
    let nvim_version = ci_nvim_version();

    let protected_of = |kind: CoverageKind| -> Vec<&KeybindCoverage> {
        entries
            .iter()
            .filter(|entry| {
                entry.kind == kind && matches!(entry.state, CoverageState::Protected { .. })
            })
            .collect()
    };
    let oracle_entries = protected_of(CoverageKind::VimOracle);
    let regression_entries = protected_of(CoverageKind::NeviRegression);
    let config_entries = protected_of(CoverageKind::ConfigMapping);
    let gaps = keybind_coverage::uncovered_entries();

    let case_counts: Vec<(&str, usize)> = vim_oracle::oracle_case_counts().collect();
    let total_cases: usize = case_counts.iter().map(|(_, count)| count).sum();
    let case_breakdown = case_counts
        .iter()
        .map(|(name, count)| format!("{name} ({count})"))
        .collect::<Vec<_>>()
        .join(", ");

    let protected_test_id = |entry: &KeybindCoverage| -> &'static str {
        match entry.state {
            CoverageState::Protected { test_id } => test_id,
            CoverageState::NeedsCoverage { .. } => unreachable!("filtered to protected entries"),
        }
    };

    let mut out = String::new();
    let _ = writeln!(
        out,
        "<!-- @generated by src/parity_report.rs — do not edit by hand.\n\
         Regenerate: NEVI_UPDATE_PARITY=1 cargo test parity_report -->\n"
    );
    let _ = writeln!(out, "# Vim/Neovim Parity Scoreboard\n");
    let _ = writeln!(
        out,
        "Nevi aims for full Vim/Neovim keybind compatibility — and backs the claim with\n\
         tests instead of adjectives. This page is generated from the same inventories\n\
         the test suite enforces, so it cannot drift from what is actually verified.\n"
    );

    let _ = writeln!(out, "## Summary\n");
    let _ = writeln!(
        out,
        "- **{implemented} keybinds implemented** ([KEYBINDINGS.md](KEYBINDINGS.md)), \
         **{planned} planned** ([KEYBINDS_ROADMAP.md](KEYBINDS_ROADMAP.md))"
    );
    let _ = writeln!(
        out,
        "- **{} keybinds in the coverage inventory**, each mapped to the automated test \
         that protects it:",
        oracle_entries.len() + regression_entries.len() + config_entries.len() + gaps.len()
    );
    let _ = writeln!(
        out,
        "  - {} verified against real Neovim ({nvim_version}) by the Vim oracle",
        oracle_entries.len()
    );
    let _ = writeln!(
        out,
        "  - {} protected by focused Nevi regression tests",
        regression_entries.len()
    );
    let _ = writeln!(
        out,
        "  - {} covered as default-keymap plumbing with dedicated tests",
        config_entries.len()
    );
    let _ = writeln!(out, "- **{total_cases} oracle cases**: {case_breakdown}");
    let _ = writeln!(out, "- **{} tracked coverage gaps**\n", gaps.len());

    let _ = writeln!(out, "## How the Vim oracle works\n");
    let _ = writeln!(
        out,
        "Each oracle case is an initial buffer plus a literal key sequence. The keys are\n\
         replayed in Nevi and in `nvim --headless`, and the resulting buffer content,\n\
         cursor position, viewport top, and mode are compared. Cases run\n\
         deterministically in the normal test suite; CI additionally replays them\n\
         against a pinned real Neovim ({nvim_version}) on macOS and Linux\n\
         (`NEVI_VIM_ORACLE=1`). A failure report includes both editors' snapshots.\n"
    );
    let _ = writeln!(
        out,
        "The coverage inventory (`src/keybind_coverage.rs`) is itself enforced by tests:\n\
         entries must be unique and complete, oracle references must name real cases,\n\
         and any gap must carry an explicit written reason — a keybind cannot silently\n\
         claim protection.\n"
    );

    let _ = writeln!(out, "## Verified against real Neovim\n");
    push_table(&mut out, "Oracle case", &oracle_entries, protected_test_id);

    let _ = writeln!(out, "## Protected by Nevi regression tests\n");
    let _ = writeln!(
        out,
        "Nevi-owned behavior with no Vim equivalent to compare against.\n"
    );
    push_table(&mut out, "Test", &regression_entries, protected_test_id);

    let _ = writeln!(out, "## Default-keymap plumbing\n");
    push_table(&mut out, "Test", &config_entries, protected_test_id);

    let _ = writeln!(out, "## Tracked gaps\n");
    if gaps.is_empty() {
        let _ = writeln!(
            out,
            "None — every inventoried keybind is currently protected by a test."
        );
    } else {
        let _ = writeln!(out, "| Keybind | Behavior | Reason |");
        let _ = writeln!(out, "|---------|----------|--------|");
        for entry in &gaps {
            let CoverageState::NeedsCoverage { reason } = entry.state else {
                continue;
            };
            let _ = writeln!(
                out,
                "| `{}` | {} | {} |",
                escape_cell(entry.key),
                escape_cell(entry.description),
                escape_cell(reason),
            );
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::{PARITY_PATH, manifest_path, render};
    use std::fs;

    /// Expect-test style: `NEVI_UPDATE_PARITY=1 cargo test parity_report`
    /// rewrites PARITY.md; a plain run fails if the committed file is stale.
    #[test]
    fn parity_md_is_up_to_date() {
        let expected = render();
        let path = manifest_path(PARITY_PATH);

        if std::env::var_os("NEVI_UPDATE_PARITY").is_some() {
            fs::write(&path, &expected).expect("write PARITY.md");
            return;
        }

        let actual = fs::read_to_string(&path).unwrap_or_default();
        if actual != expected {
            let first_diff = actual
                .lines()
                .zip(expected.lines())
                .position(|(a, b)| a != b)
                .map(|idx| idx + 1);
            panic!(
                "PARITY.md is stale (first differing line: {first_diff:?}).\n\
                 Regenerate with: NEVI_UPDATE_PARITY=1 cargo test parity_report"
            );
        }
    }
}
